Phone Validation on the contact us form.
odoo-dev/odoo pull request #119
Opened 2017-01-27 13:10 UTC by jpr-odoo

Task: https://www.odoo.com/web?#id=30897&view_type=form&model=project.task&action=333&active_id=131&menu_id=4720
Pad: https://pad.odoo.com/p/r.0ef60fba3a837ccfe5814f24c68c219b

2017-02-23 10:58 UTC, rim-odoo requested changes

2017-02-23 10:58 UTC, rim-odoo commented on addons/crm_phone_valid/models/crm_lead.py
> +                raise UserError(_('Unable to parse the contact (phone,mobile,fax) number!'))
`parse` is rather a technical word... "validate" would be more easy to understand

2017-02-23 10:58 UTC, rim-odoo commented on addons/crm_phone_valid/models/crm_lead.py
> +                raise UserError(_('Invalid contact (phone,mobile,fax) number, too few or too much digits!'))
```python
replace("too much","too many")
```

2017-02-23 10:58 UTC, rim-odoo commented on addons/crm_phone_valid/models/crm_lead.py
> +                raise UserError(_('Invalid contact (phone,mobile,fax) number, the prefix does not belong to a valid NPA!'))
Ẁhat is a NPA? Sounds like a technical word.

2017-02-23 10:58 UTC, rim-odoo commented on addons/website_crm_phone_validate/controllers/main.py
> +            for cantact in contact_number:
cantact? probably a typo ;-)

2017-04-13 09:06 UTC, tde-banana-odoo commented
Included in https://github.com/odoo/odoo/pull/16412/files . Thanks !

2017-04-13 09:06 UTC, closed without merging