[IMP] l10n_in{_edi}: GSTR1 & GSTR-3B reports
odoo-dev/odoo pull request #1292
Opened 2022-07-06 13:46 UTC by epictete

2022-07-06 13:47 UTC, robodoo commented
This PR targets the un-managed branch odoo-dev/odoo:master-reportalypse-oco, it can not be merged.

2022-07-08 12:42 UTC, oco-odoo requested changes

2022-07-08 12:42 UTC, oco-odoo commented on addons/l10n_in/data/account_tax_tag_data.xml
> +    <!-- GST Base tax tag -->
Let's rather declare them in csv (waaay less lines, and the data are simple enough that we can afford that)

2022-07-08 12:42 UTC, oco-odoo commented on addons/l10n_in/data/account_tax_template_data.xml
> +        <field name="invoice_repartition_line_ids" eval="[(5, 0, 0),             (0,0, {                 'factor_percent': 100,                 'repartition_type': 'base',             'tag_ids': [ref
Fix spacing in this file. I don't know if it was already like that, but for these, we want to use multiple lines, else it's unreadable.

2022-07-08 12:42 UTC, oco-odoo commented on addons/l10n_in/data/account_tax_template_data.xml
> +    <record id="non_gst_supplies_purchase" model="account.tax.template">
We're adding a bunch of new taxes. It's not the place to do this. Remove them from your PR, and tell JVA to do that in his branch, not here.

2022-07-08 12:42 UTC, oco-odoo commented on addons/l10n_in_edi/models/account_edi_format.py
> +                "uin_holders",
What's that ?

2022-07-08 12:42 UTC, oco-odoo commented on addons/l10n_in_edi/models/account_edi_format.py
> +            if tax_line.tax_tag_ids in self.env.ref("l10n_in.tax_tag_cess"):
```suggestion
            if self.env.ref("l10n_in.tax_tag_cess") in tax_line.tax_tag_ids:
```

I guess this makes more sense, right ?

2022-07-08 12:42 UTC, oco-odoo commented on addons/l10n_in_edi/models/account_edi_format.py
> +            elif tax_line.tax_tag_ids in self.env.ref("l10n_in.tax_tag_state_cess"):
```suggestion
            elif self.env.ref("l10n_in.tax_tag_state_cess") in tax_line.tax_tag_ids:
```

2022-07-08 12:42 UTC, oco-odoo commented on addons/l10n_in_edi/models/account_edi_format.py
> +                    if tax_line.tax_tag_ids in self.env.ref("l10n_in.tax_tag_%s"%(gst)):
```suggestion
                    if self.env.ref("l10n_in.tax_tag_%s"%(gst)) in tax_line.tax_tag_ids:
```

2022-07-08 12:42 UTC, oco-odoo commented on addons/l10n_in_edi/models/account_edi_format.py
> +                    if tax_line.tax_tag_ids in self.env.ref("l10n_in.tax_tag_%s"%(gst)):
Also, rather do the ref *before* the loop.

2022-07-12 12:50 UTC, epictete commented on addons/l10n_in_edi/models/account_edi_format.py
> +                "uin_holders",
It's used in `enterprise/l10n_in_reports/data/account_financial_html_report_gstr3b.xml`

2022-07-12 14:44 UTC, oco-odoo commented
Cherry-picked

2022-07-12 14:44 UTC, closed without merging