Master reportalypse vin l10n fix
odoo-dev/odoo pull request #1309
Opened 2022-07-14 13:46 UTC by vin-odoo

2022-07-14 13:47 UTC, robodoo commented
This PR targets the un-managed branch odoo-dev/odoo:master-reportalypse-oco, it can not be merged.

2022-07-18 21:14 UTC, oco-odoo requested changes

2022-07-18 21:14 UTC, oco-odoo commented on addons/l10n_eg/data/account_tax_report_data.xml
> +                        <field name="formula">STDR_SALE_B.balance + ZEROR_SALE_B.balance + EXMP_SALE_B.balance</field>
Why all these changes ?

2022-07-18 21:14 UTC, oco-odoo commented on addons/stock_account/tests/test_stockvaluationlayer.py
> +class TestAngloSaxonAccounting(AccountTestInvoicingCommon):
What's that ? Why is it done so ? Does it have anything to do with this branch or is it a fix for a problem already present in master ?

2022-07-19 06:21 UTC, vin-odoo commented on addons/l10n_eg/data/account_tax_report_data.xml
> +                        <field name="formula">STDR_SALE_B.balance + ZEROR_SALE_B.balance + EXMP_SALE_B.balance</field>
There is another report using the same line code, it causes issues when both are installed

2022-07-19 06:22 UTC, vin-odoo commented on addons/stock_account/tests/test_stockvaluationlayer.py
> +class TestAngloSaxonAccounting(AccountTestInvoicingCommon):
It's running with the current company and thus is impacted by all things localisations.
IT's a fix for master problem, not reportalypse

2022-07-19 09:44 UTC, oco-odoo commented on addons/l10n_eg/data/account_tax_report_data.xml
> +                        <field name="formula">STDR_SALE_B.balance + ZEROR_SALE_B.balance + EXMP_SALE_B.balance</field>
Then let's prefix them both with country code

2022-07-19 09:45 UTC, oco-odoo commented on addons/stock_account/tests/test_stockvaluationlayer.py
> +class TestAngloSaxonAccounting(AccountTestInvoicingCommon):
@Shawcker Could you remove this from this branch, create a new PR in master and have the stock team review it ?

2022-07-19 13:11 UTC, oco-odoo requested changes

2022-07-19 13:11 UTC, oco-odoo commented on addons/l10n_it_edi/models/account_edi_format.py
> +                return True
report_lines = self.env['account.report.line'].search([('report_id.country_id.code', '=', 'IT'), ('code', 'like', 'machin')])
vj_tags = report_lines.expression_ids._get_matching_tags()
return bool(vj_tags & invoice_lines_tag_ids)

Something like that :p 

@Shawcker

2022-07-19 13:11 UTC, oco-odoo commented on addons/l10n_it_edi/models/account_edi_format.py
> +        return False
idem

2022-07-19 14:26 UTC, merged