[IMP] web: `kanban`, adapt for dark mode
odoo-dev/odoo pull request #1338
Opened 2022-09-22 12:11 UTC by xlu-odoo

task-2710677

2022-09-22 12:11 UTC, robodoo commented
This PR targets the un-managed branch odoo-dev/odoo:master-dark-mode-sri, it needs to be retargeted before it can be merged.

2022-09-23 10:54 UTC, stefanorigano requested changes

2022-09-23 10:54 UTC, stefanorigano commented on addons/web/static/src/legacy/scss/kanban_view.scss
> +            color: map-get($o-theme-text-colors, 'danger');
it should be `o-text-color($key)`

2022-09-26 08:03 UTC, xlu-odoo commented on addons/web/static/src/legacy/scss/kanban_view.scss
> +            color: map-get($o-theme-text-colors, 'danger');
Updated, thanks

2022-09-26 09:36 UTC, stefanorigano approved these changes

2022-09-26 09:36 UTC, merged