[IMP] mail: message edit
odoo-dev/odoo pull request #1393
Opened 2022-11-10 12:43 UTC by tsm-odoo

2022-11-10 12:44 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo-dev/odoo/pull/1393).

2022-11-10 22:02 UTC, alexkuhn requested changes
Not easy to see editing message when it keeps same background as message in non-edit.
Also composer buttons have different colors:

<img width="979" alt="branch" src="https://user-images.githubusercontent.com/6569390/201215064-3fea48e6-34df-4b56-98cb-bd9319fc3bea.png">

This is the visual we have in master:

<img width="974" alt="master" src="https://user-images.githubusercontent.com/6569390/201215112-d326aaa0-951a-481a-82a3-a12f35aa7917.png">

Which is much better, as we see clearly the editing message with a white background.

2022-11-10 22:02 UTC, alexkuhn commented on addons/mail/static/src/thread/message.xml
> +                    </t>
Note that `t-if` can be immediately on `<div>` (makes template more readable)

2022-11-10 22:02 UTC, alexkuhn commented on addons/mail/static/src/thread/message.xml
> +                        <Composer t-else="" autofocus="true" message="message" onDiscardCallback.bind="onEditDone" onPostCallback.bind="onEditDone" mode="'compact'" />
This is wrong placement. I think we made the exact same problem in `master` and `16.0`, and because of this we have to deal with special styling selector for special content, e.g. mail content that make use of `table`, for which we need to do some styling lifting to have consistent rendering as in any other mail client.

One of the problem is that `Composer` elements are affected by these styling rules:
https://github.com/odoo/odoo/blob/16.0/addons/mail/static/src/components/message/message.scss#L27

And we recently had to do some special bug fixing as a result of this bad placement:
https://github.com/odoo/odoo/pull/105162

What we actually want here is distinguishing `editableContent` and not a (non-editable) `content`, so that composer is `editableContent`. That way, the problematic SCSS that we'll need to reintroduce will not affect the `Composer`.

2022-11-10 22:02 UTC, alexkuhn commented on addons/mail/static/src/composer/composer.js
> +    }
Can `this.ref.el` be undefined? I don't see any conditional on presence of `textarea` in the template.

2022-11-10 22:02 UTC, alexkuhn commented on addons/mail/static/src/composer/composer.js
> +        useEffect(() => this.resizeTextArea(), () => [this.state.value, this.ref.el]);
This resize feature can be its own PR.
Would reduce complexity of this PR, and allow merging this faster than edit, if there are more review and code changes to do.

2022-11-10 22:02 UTC, alexkuhn commented on addons/mail/static/src/composer/composer.js
> +        });
Some syncing issue with current implementation:
- if props `message` or `thread` change but it keeps the same `Composer`, the local attributes `message` and `thread` still refer to old `message`/`thread`.
- if props `message` change (or just its `body`) but it keeps the same `Composer`, then `state.value` is not updated accordingly (still contains previous message inline content.
- if props change from having a message to no message (or vice-versa) but it keeps the same `Composer`, then the local attribute `isInEditMode` is not updated accordingly.

Storing local attributes introduce syncing issues, which would need some hooks to update them, like `onWillUpdateProps()`. For the once that are just read-only, might be wiser to not introduce the local attributes and instead just use a `get`ter

2022-11-10 22:02 UTC, alexkuhn commented on addons/mail/static/src/composer/composer.js
>              () => [this.props.autofocus + this.state.autofocus, this.props.placeholder]
Out-of-scope of PR, but having `this.props.placeholder` in list of dependencies look like a hack.
From my understanding on what issue it's attempting to solve, is to do focus again when there is an active action to the user that is expecting to focus the composer.

This relies on the fact that Send message/log note have different placeholder. This is just a preference to have different placeholder. What I mean is that even if we choose to have same placeholder, autofocus should still work. Hence why this hack should not exist in the 1st place.

2022-11-10 22:02 UTC, alexkuhn commented on addons/mail/static/src/composer/composer.js
> +        } else if (ev.keyCode === KEY_CODES.ESCAPE) {
`keyCode` is deprecated, should use `key`. It has a functionally meaningful value like "Enter" or "Escape", so no need for an `utils`.

2022-11-10 22:02 UTC, alexkuhn commented on addons/mail/static/src/composer/composer.js
> +        if(this.isInEditMode) {
Missing whitespace between `if` and `(` (please properly configure linter and prettier)

2022-11-10 22:02 UTC, alexkuhn commented on addons/mail/static/src/composer/composer.js
>      async sendMessage() {
Mame of method is misleading. It's not a "send" when it `isInEditMode`.

Properly define 2 distinct methods `sendMessage` and `editMessage`.
Keydown `ENTER` should call appropriate method depending on `isInEditMode` (or actually presence of `props.message`, as I said in a previous comment there are syncing issue of storing local attributes!!!).

2022-11-10 22:02 UTC, alexkuhn commented on addons/mail/static/src/composer/composer.js
> +    }
I wouldn't define such method `reset`.
It's tempting to combine both LOCs as a `reset()` method, but only the 1st LOC is conceptually correct.
Self-focus is feature and context-dependent, so it's incorrect to say that any reset is always a self-focus.

Keeping `reset()` is not super useful now, but may eventually become relevant if we introduce more state that properly need some assignment for "reset". I'm quite indifferent to introduce now (or maybe later?)

2022-11-10 22:02 UTC, alexkuhn commented on addons/mail/static/src/thread/message.js
> +    }
These methods are not that useful. Could just assign `state.isEditing` where needed, so that there are less concepts to introduce (here the 2 names methods).

2022-11-10 22:02 UTC, alexkuhn commented on addons/mail/static/src/thread/message.js
> +        useExternalListener(document, "mousedown", this.onClickAway);
`click` is a better UX than `mousedown`.
- `mousedown` commits even when accidental click, and user cannot recover a `mousedown` with a following `mouseup` on the input itself.
- `click` requires `mousedown` and following `mouseup` outside of textarea, which more clearly define the proper commitment to click away.

So all in all, replace `mousedown` by `click`.

2022-11-10 22:02 UTC, alexkuhn commented on addons/mail/static/src/thread/message.js
> +    }
Dedicated method is not useful, would just make an arrow function on `useExternalListener`

2022-11-10 22:02 UTC, alexkuhn commented on addons/mail/static/src/thread/message.js
> +        }
This leaks `EmojiPicker` feature.

This is bad because whenever a special feature shows a floating content like this emoji picker is changed/added/removed, we must maintain this code.

It wouldn't be too bad if this was `Composer` itself, but even so, a floating content inside another floating content would also have the same issue. _(IIRC, we have a popover in a popover in a mark-as-done screen in kanban view, on activity widget I think)_

The problem with `el.contains()` is that it's based on DOM children, not on functional group of feature. Floating content like `Popover` are content not in DOM children, so `el.contains` fail for them.
Normally should use something else than `el.contains`.

The component way is with `props`, so somehow should pass a `onContains` callback, which is invoked when parent needs to solve a `.contains()` (floating elements included). Could pass this to `EmojiPicker` for the moment. Would have been nice that this implementation exists for all `Popover`.

2022-11-10 22:02 UTC, alexkuhn commented
This is just a 1st pass review. There were already many comments, so I prefer making code changes from this 1st review before continuing.

2022-11-14 10:39 UTC, tsm-odoo commented on addons/mail/static/src/composer/composer.js
> +        useEffect(() => this.resizeTextArea(), () => [this.state.value, this.ref.el]);
Moved in its own PR :+1:

2022-11-14 11:02 UTC, tsm-odoo commented on addons/mail/static/src/composer/composer.js
> +    }
Let's say later, as you said there is no evidence that reset will always need to be followed by a self focus, and for now this method only saves 2 lines which is not enough to justify its introduction :t-rex:

2022-11-14 12:56 UTC, tsm-odoo commented
@alexkuhn I applied your suggestions, I don't know where the first screenshot comes from but it looks like the one below on local/the last runbot build :+1:

2022-11-14 16:17 UTC, alexkuhn commented on addons/mail/static/src/thread/message.js
> +        this.messageRef = useRef("messageRef");
Would just name it `ref`, just because it's shorter.

2022-11-14 16:17 UTC, alexkuhn commented on addons/mail/static/tests/helpers/test_server.js
> +        };
I think you want `...result` at the end, so that it overwrites what was in `this.messages[id]` before

2022-11-14 16:17 UTC, alexkuhn commented on addons/mail/static/tests/message/message_tests.js
> +        assert.containsN(target, ".o-mail-composer", 2);
Would be best for assertion to target more specifically the editing composer

2022-11-14 16:17 UTC, alexkuhn commented on addons/mail/static/tests/message/message_tests.js
> +        assert.containsN(target, ".o-mail-composer", 2);
Again would be best to target specifically the editing composer

2022-11-14 17:02 UTC, alexkuhn commented
👆Just remove `isInEditMode` getter, so that rest of code just relies on `props.message`

2022-11-14 17:02 UTC, merged