[IMP] mail: improve emoji picker style
odoo-dev/odoo pull request #1395
Opened 2022-11-10 14:40 UTC by alexkuhn

- visibly better in dark theme
- align emoji position
- grayscale on non-hover emoji top item
- softer separator between search bar and content

2022-11-10 14:41 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo-dev/odoo/pull/1395).

2022-11-15 16:31 UTC, Nemael requested changes

2022-11-15 16:31 UTC, Nemael commented on addons/mail/static/src/composer/emoji_picker.scss
> +        filter: grayscale(1);
The grayscale for non-selected categories is great, but it now is hard to tell which category is currently selected.

It would be clearer to remove grayscale on hovered category and on selected category, to be able to tell apart a selected category from a non-selected one.

2022-11-15 16:31 UTC, Nemael commented on addons/mail/static/src/composer/emoji_picker.xml
> +                <input class="form-control border-0 flex-grow-1" t-ref="input" placeholder="Search an emoji" t-model="state.searchStr"/>
"Search for an emoji" is a more accurate as a placeholder text
"Search an emoji" means that an emoji is "searched" to find something within it.

2022-11-15 17:47 UTC, alexkuhn commented on addons/mail/static/src/composer/emoji_picker.scss
> +        filter: grayscale(1);
changes done (non-grayscale for active category)

2022-11-15 17:48 UTC, alexkuhn commented on addons/mail/static/src/composer/emoji_picker.xml
> +                <input class="form-control border-0 flex-grow-1" t-ref="input" placeholder="Search an emoji" t-model="state.searchStr"/>
changes to "Search for an emoji", as suggested

2022-11-17 15:21 UTC, merged