[FIX] mail: fix inserting emoji at the correct position
odoo-dev/odoo pull request #1398
Opened 2022-11-10 15:17 UTC by Nemael

This commit fixes emojis that were not inserted in the correct position in the composer

2022-11-10 15:18 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo-dev/odoo/pull/1398).

2022-11-15 15:48 UTC, alexkuhn requested changes

2022-11-15 15:48 UTC, alexkuhn commented on addons/mail/static/src/composer/composer.js
> +        this.state.value = this.state.value.substring(0, caret_position) + str + this.state.value.substring(caret_position, this.state.value.length);
When adding emoji, it should concatenate as follow:
- before selection start
- replace between selection start-end with emoji
- after selection end

That way it properly handles any case of selection.

2022-11-15 17:35 UTC, alexkuhn commented on addons/mail/static/src/composer/composer.js
> +                    }
Linter/prettier not happy with these LOCs,

Make sure to configure them properly on your machine. See `@web/tooling` (notably `enable.sh`)

2022-11-15 17:35 UTC, alexkuhn commented on addons/mail/static/src/composer/composer.js
> +                    }
I was wondering why it was not just simply after `addEmoji` LOCs, but the current implementation of `useEffect` has side-effect to re-focus at the end of composer input...

`useEffect` is a bad smell equivalent to our `onChange` in the previous code of discuss. We should avoid it as much as possible.

I would suggest doing something to remove this `useEffect`. Make a test for coverage of chatter change of send message/log not in chatter, and reimplement a solution without this `useEffect`. If doing properly, then this "restore" of caret position should be applied immediately after `addEmoji`, not in a following `onChange`

2022-11-21 16:20 UTC, alexkuhn commented
Again should rebase with target branch (commit history was changed)

2023-02-06 15:32 UTC, seb-odoo commented
Do we still need this PR?

2023-02-06 15:39 UTC, Nemael commented
> 

No, it was included in another PR, this one can be closed.

2023-02-06 15:43 UTC, closed without merging