[REF] mail: use confirm dialog instead of custom dialog for delete
odoo-dev/odoo pull request #1407
Opened 2022-11-15 12:32 UTC by ged-odoo

The preview for a deleted message can simply be the content of the message body, not necessarily a message component.

2022-11-15 12:33 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo-dev/odoo/pull/1407).

2022-11-15 13:33 UTC, alexkuhn requested changes
It's ok to use `ConfirmDialog`, but we should not remove the visual of a `Message` without action in the content of dialog.
I'd say `ConfirmDialog` should allow slot for it's content, so that we can use `<Message>`.

2022-11-22 16:44 UTC, seb-odoo commented
PR messed up but I believe there is a new one now?

2022-11-22 22:36 UTC, alexkuhn commented
Duplicate of https://github.com/odoo-dev/odoo/pull/1426
Newer PR is more up-to-date, so closing this one.

2022-11-22 22:36 UTC, closed without merging