[FIX] mail: autogrow-input-width-zel
odoo-dev/odoo pull request #1425
Opened 2022-11-18 16:45 UTC by zel-odoo

2022-11-18 16:45 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo-dev/odoo/pull/1425).

2022-11-23 12:04 UTC, seb-odoo requested changes
I didn't check the code, but it doesn't work as expected.

copy from chat:

what issue is it trying to resolve?
I can still overflow the input with the PR
and when empty it is still too small
also it is very laggy when typing on this PR, for example keeping a key pressed it is extremely slow

2022-11-23 20:17 UTC, zel-odoo commented
@alexkuhn I did some search and found that it is not possible with only an input element to create a resizable input. either we have to use a `<span> trick` or use `size` attribute trick, or the purely js trick like gery did. However, all of them cannot solve the width problem if we are using a flex layout. Becasue all the trick is to manually set the `width` with an absolute value and this conflicts with the flex layout. so I used this trick, to make it a `<div>`. With this it can be easily and beautifully resized according to the content without using the absolute value.

However, there are two things unsolved.
1. the placeholder will not be as good as it is in input, and the way we handle it will be creepy ( cause we should treat the placeholder as an innterText but not the `state.value`)
2. I tried to use the flex grid to make the width problem work but it seems still having problems. I got stuck on this for too long, so maybe I think there is something missing and I cannot see it. can you help me to have a look at that if you have any ideas? Thanks

2022-11-24 12:23 UTC, alexkuhn commented
Works wonderfully, thank!

2022-11-24 12:23 UTC, merged