[IMP] mail: change topbar thread description
odoo-dev/odoo pull request #1435
Opened 2022-11-21 12:03 UTC by zel-odoo

2022-11-21 12:03 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo-dev/odoo/pull/1435).

2022-11-21 14:17 UTC, alexkuhn requested changes

2022-11-21 14:17 UTC, alexkuhn commented on addons/mail/static/src/new/discuss/discuss.xml
> +                        />
If you update description to empty string, then it's not possible to edit description anymore :-(

2022-11-21 14:20 UTC, alexkuhn commented
Also make sure to reuse same history as target `master-discuss-refactoring`.
When I tried to rebase, somehow there was a conflict in `web/package.json`

2023-02-06 15:33 UTC, seb-odoo commented
Do we still need this PR?

2023-02-14 13:50 UTC, alexkuhn commented
Let's just drop the PR. If we need it at some point, let's just redo it from scratch

2023-02-14 13:50 UTC, closed without merging