[IMP] persist composer content when switching channels
odoo-dev/odoo pull request #1460
Opened 2022-11-24 14:07 UTC by oomsveta

2022-11-24 14:08 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo-dev/odoo/pull/1460).

2022-11-24 14:27 UTC, alexkuhn requested changes
Tests do not pass

2022-11-24 14:27 UTC, alexkuhn commented on addons/mail/static/src/new/discuss/discuss.xml
> +                <Composer t-key="thread.id" composer="thread.composer" autofocus="true" highlightReplyTo="messageHighlight.highlightMessage" onDiscardCallback="() => messaging.cancelReplyTo()" dropzo
When using `reply` feature on `inbox`, should pass composer of origin thread of message, rather than `inbox`

2022-11-24 14:27 UTC, alexkuhn commented on addons/mail/static/src/new/messaging.js
> +        }
Why not? Not that it makes sense for our specs, but no reason to restrict on `inbox` and not `starred`.
It's the code that uses `inbox.composer` that is wrong. See previous comment

2022-11-25 10:45 UTC, oomsveta commented
@alexkuhn tests fixed

2022-11-25 12:41 UTC, merged