[FIX] mail: Fix failed tests (message and chat)
odoo-dev/odoo pull request #1923
Opened 2023-01-23 16:50 UTC by maki-odoo

2023-01-23 16:51 UTC, robodoo commented
[Pull request status dashboard](https://mergebot.odoo.com/odoo-dev/odoo/pull/1923).

2023-01-23 16:52 UTC, seb-odoo commented on addons/mail/static/tests/qunit_suite_tests/widgets/form_renderer_tests.js
> +            assert.containsOnce(
skipped test should not be adapted this way

2023-01-23 18:06 UTC, seb-odoo commented on addons/mail/static/tests/new/chat/chat_window_tests.js
> +        await triggerEvent(target, ".o-mail-composer-textarea", "keydown", {
just the syntax change is good, no need to remove the next render

2023-01-23 18:07 UTC, seb-odoo commented on addons/mail/static/tests/new/message/message_tests.js
> -        await afterNextRender(() => advanceTime(50 * 1000)); // next fetch of im_status
need to investigate why it doesn't work

2023-01-24 13:19 UTC, seb-odoo commented
I think the PR is no longer necessary, you could rebase and see what's left to resolve (if anything).

2023-01-24 13:20 UTC, alexkuhn requested changes
This PR looks irrelevant: all tests pass.
Do you agree?

2023-01-24 13:45 UTC, closed without merging