[IMP] mail, im_livechat: convert livechat to OWL - WIP
odoo-dev/odoo pull request #200
Opened 2020-03-03 15:51 UTC by seb-odoo

2020-03-04 15:00 UTC, seb-odoo commented
@alexkuhn backend part of livechat, should be done as best as possible without entity

2020-03-09 11:21 UTC, alexkuhn requested changes

2020-03-09 11:21 UTC, alexkuhn commented on addons/im_livechat/models/im_livechat_channel.py
> +            image_128 = base64.b64encode(image_file.read())
still unsure how to solve this issue, so let's keep older logic instead: use this source when channel of type `livechat`.

2020-03-09 11:21 UTC, alexkuhn commented on addons/im_livechat/static/src/owl/components/chat_window_header/chat_window_header.xml
> +            </t>
Livechat may have an icon, notably when visitor is typing.

2020-03-09 11:21 UTC, alexkuhn commented on addons/im_livechat/static/src/owl/components/discuss/discuss_tests.js
> +});
test already in `/mail`, and is unrelated to patches from `/im_livechat`

2020-03-09 11:21 UTC, alexkuhn commented on addons/im_livechat/static/src/owl/components/discuss/discuss_tests.js
> +        debug: 1,
no `debug`

2020-03-09 11:21 UTC, alexkuhn commented on addons/im_livechat/static/src/owl/components/discuss_sidebar/discuss_sidebar.js
> +            return nameVal.indexOf(qsVal) !== -1;
`.includes()`

2020-03-09 11:21 UTC, alexkuhn commented on addons/mail/static/src/owl/components/chat_window_header/chat_window_header.js
> +            // used in threadName getter
then why not use this getter here?

2020-03-09 11:47 UTC, seb-odoo commented on addons/im_livechat/static/src/owl/components/discuss/discuss_tests.js
> +});
it was used as reference, removed

2020-03-09 11:47 UTC, seb-odoo commented on addons/im_livechat/static/src/owl/components/discuss/discuss_tests.js
> +        debug: 1,
ok

2020-03-09 11:49 UTC, seb-odoo commented on addons/im_livechat/static/src/owl/components/discuss_sidebar/discuss_sidebar.js
> +            return nameVal.indexOf(qsVal) !== -1;
ok, I changed also the occurrences where I copied it from

2020-03-09 12:15 UTC, seb-odoo commented on addons/im_livechat/static/src/owl/components/chat_window_header/chat_window_header.xml
> +            </t>
I added the icon on the header.

2020-03-09 12:19 UTC, seb-odoo commented on addons/mail/static/src/owl/components/chat_window_header/chat_window_header.js
> +            // used in threadName getter
I misread the old code here, partially reverted

2020-03-09 12:31 UTC, seb-odoo commented on addons/im_livechat/models/im_livechat_channel.py
> +            image_128 = base64.b64encode(image_file.read())
Done, added the override in thread preview.

After entities it should probably be a getter on thread.

2020-03-09 12:46 UTC, seb-odoo commented
All changes done, waiting runbot

2020-03-09 13:08 UTC, seb-odoo commented
green except migration

2020-03-09 14:00 UTC, alexkuhn approved these changes

2020-03-09 14:00 UTC, merged