Allow the hide/show of activities/followers/thread based on form view arch
odoo-dev/odoo pull request #210
Opened 2020-03-18 16:01 UTC by xdu-odoo

2020-03-18 16:15 UTC, seb-odoo commented
This is probably a fix for task-2208259 btw

2020-03-19 09:17 UTC, seb-odoo requested changes
I like this is simple, overall looks ok, see for some details below.

Maybe we should add a test for it since it isn't covered at all since runbot was green before.

2020-03-19 09:17 UTC, seb-odoo commented on addons/mail/static/src/owl/store/messaging_actions.js
> +            initialThreadModel
```suggestion
            initialThreadModel,
```

2020-03-19 09:17 UTC, seb-odoo commented on addons/mail/static/src/owl/store/messaging_actions.js
> +            threadModel
```suggestion
            threadModel,
```

2020-03-19 09:17 UTC, seb-odoo commented on addons/mail/static/src/owl/store/messaging_actions.js
> +            hasThread,
default true (for documents)

2020-03-19 09:17 UTC, seb-odoo commented on addons/mail/static/src/js/form_renderer.js
> +     * Determine whether the chatter of the form renderer should display thread
dot at the end and keep line below 80 chars

2020-03-19 09:17 UTC, seb-odoo commented on addons/mail/static/src/js/form_renderer.js
> +     * Determine whether the chatter of the form renderer should display activities
3rd person ("returns"), dot at the end, and limit to 80 char per line. (same for 2 other other methods below)

2020-03-19 12:04 UTC, seb-odoo requested changes
Still need to create a test as discussed.

Minor code stuff below.

2020-03-19 12:04 UTC, seb-odoo commented on addons/mail/static/src/js/form_renderer.js
> +     * Determine whether the chatter of the form renderer should display
3rd person here too
```suggestion
     * Returns whether the chatter of the form renderer should display
```

2020-03-19 12:04 UTC, seb-odoo commented on addons/mail/static/src/js/form_renderer.js
> +     * Determine whether the chatter of the form renderer should display
```suggestion
     * Returns whether the chatter of the form renderer should display
```

2020-03-19 12:04 UTC, seb-odoo commented on addons/mail/static/src/js/form_renderer.js
> +     * Determine whether the chatter of the form renderer should display thread.
```suggestion
     * Returns whether the chatter of the form renderer should display thread.
```

2020-03-19 12:04 UTC, seb-odoo commented on addons/mail/static/tests/owl/form_renderer_chatter_tests.js
> +        }]
```suggestion
        }],
```

2020-03-19 12:04 UTC, seb-odoo commented on addons/mail/static/tests/owl/form_renderer_chatter_tests.js
> +            name: {string: "Name", type: 'char', default: ' '},
Remove default if not needed, or put a real value if needed. This looks like a typo.

```suggestion
            name: { string: "Name", type: 'char' },
```

2020-03-19 12:04 UTC, seb-odoo commented on addons/mail/static/tests/owl/form_renderer_chatter_tests.js
> +            message_ids: {string: "Messages", type: 'one2many', relation: 'mail.message'},
```suggestion
            message_ids: { string: "Messages", type: 'one2many', relation: 'mail.message' },
```

2020-03-19 14:06 UTC, seb-odoo requested changes

2020-03-19 14:06 UTC, seb-odoo commented on addons/mail/static/tests/owl/form_renderer_chatter_tests.js
> +    );
We try to use the helpers now:

```suggestion
    assert.containsOnce(document.body, `.o_Chatter`,
        "there should still be a chatter"
    );
```

Same for all the others.

2020-03-19 14:06 UTC, seb-odoo commented on addons/mail/static/tests/owl/form_renderer_chatter_tests.js
> +    assert.strictEqual(
`containsNone`

See `qunit_asserts.js` for all the possibilities

2020-03-19 14:06 UTC, seb-odoo commented on addons/mail/static/tests/owl/form_renderer_chatter_tests.js
> +                type: 'integer'
trailing `,` (to double check all of them)

2020-03-19 14:06 UTC, seb-odoo commented on addons/mail/static/tests/owl/form_renderer_chatter_tests.js
> +    this.data['res.partner'] = {
Fields definition should be moved in `beforeEach` to avoid repetition.

Records can stay on the tests.

2020-03-19 14:06 UTC, seb-odoo commented on addons/mail/static/tests/owl/form_renderer_chatter_tests.js
> +assert.strictEqual(
indent

2020-03-19 14:06 UTC, seb-odoo commented on addons/mail/static/tests/owl/form_renderer_chatter_tests.js
> +            name: {string: "Name", type: 'char'},
```suggestion
            name: { string: "Name", type: 'char' },
```

2020-03-19 14:06 UTC, seb-odoo commented on addons/mail/static/tests/owl/form_renderer_chatter_tests.js
> +        arch: `<form string="Partners">
Move tag to new line to keep indent with closing tag (same for other tests), similar to what was done for templates in the component.

2020-03-19 14:39 UTC, seb-odoo approved these changes
Ok for me. Last detail below. I'll let @alexkuhn final check and merge.

2020-03-19 14:39 UTC, seb-odoo commented on addons/mail/static/tests/owl/form_renderer_chatter_tests.js
> +            </form>`,
everywhere:
```suggestion
            </form>
        `,
```

2020-03-19 14:40 UTC, seb-odoo commented on addons/mail/static/tests/owl/form_renderer_chatter_tests.js
> +        "there should still be a chatter"
Remove all the "still", it doesn't make sense when there wasn't an assertion without "still" before.

2020-03-19 15:35 UTC, xdu-odoo commented
Annnnd that's a green, man !

2020-03-20 12:12 UTC, alexkuhn approved these changes

2020-03-20 12:12 UTC, alexkuhn commented
rebase then merge

2020-03-20 12:18 UTC, seb-odoo commented
Can't we just click on rebase and merge? There will be conflict/crash?

2020-03-20 12:18 UTC, seb-odoo commented
Oh I think you meant squash/fixup

2020-03-20 12:19 UTC, alexkuhn commented
oops, yes I meant squash, sorry

2020-03-20 12:44 UTC, closed without merging

2020-03-20 12:44 UTC, xdu-odoo commented
Merged.