Master milk cp dbo
odoo-dev/odoo pull request #2465
Opened 2023-05-02 15:48 UTC by bouvyd

In short;

- move 'list selection ui' to another slot that is in the same div as the searchbar (way more clean in mobile, as it has its own dedicated row)
- cogmenu: do not display actions and print entries if no records is selected (like in v16); only 'global' actions (import, add to spreadsheet, etc.) should be there if no record is selected
- change the cp layout for better mobile (and intermediary sizes) behaviour:
  - searchbar will be hidden automatically under the lg breakpoint
  - collapse 'always' buttons into 'new' dropdown and view switcher into a dropdown under lg as well
The goal is to leave enough place to the breadcrumb and the pager (when there is one), as these elements can be rather sizable in some cases.

https://user-images.githubusercontent.com/9530767/235717452-7ab320b5-956f-4fa6-9244-ccf86c893e79.mp4

2023-05-02 15:48 UTC, robodoo commented
This PR targets the un-managed branch odoo-dev/odoo:master-milk, it needs to be retargeted before it can be merged.

2023-05-02 15:49 UTC, bouvyd commented
Goes with odoo-dev/enterprise#542 - they must be merged together or you will have crashes.

2023-05-02 15:53 UTC, bouvyd commented
@stefanorigano here's a rather 'finished' POC for the control panel changes, mostly for mobile (but not only)

Since i'm off tomorrow, if it meets your approval for the class changes, you can merge (rebase and merge via the button should work fine). If not, either add commits with your desired changes and merge, or comment and i'll update it thursday

2023-05-03 17:08 UTC, stefanorigano commented
Hello @bouvyd , thanks. 

> collapse 'always' buttons into 'new' dropdown 

Problematic IMO.  **[NEW⎮▼]** let me think that the dropdown shows "other type of content" you may want to create.
It's not clear that it contains totally different actions (maybe it is clear when resizing  on desktop, but not landing on mobile directly).

'always' buttons are great exception to the entire logic since they break the correlation between [NEW], breadcrumb and title. The natural place for these action should be inside the cog menu indeed. The only reason why we placed them outside it's because some modules desperately need a "shortcut" apparently... if in mobile we have to "hide them inside the dropdown" anyways, then it's probably better to move them inside the cog instead (mobile only), what do you think? 

> cogmenu: do not display actions and print entries if no records is selected (like in v16); only 'global' actions (import, add to spreadsheet, etc.) should be there if no record is selected

This is the intended behavior indeed 👍 

> move 'list selection ui' to another slot that is in the same div as the searchbar (way more clean in mobile, as it has its own dedicated row)

LGTM 👍

2023-05-04 07:59 UTC, bouvyd commented
@stefanorigano it's not as simple as that, when discussed with fp we established that "always" buttons are (or, more accurately; should be) akin to "new" buttons, because they're there to create stuff; examples:
- Generate Leads in CRM: opens a wizard to automatically generate new records
- "Scan"/"Upload" in Expenses: create an expense from an attachment
- "Create Report" in Expenses: allows to create a report from the expenses view
- "Request" button in Documents: generate a new document request (a delayed document creation)
- "Upload a pdf"/"upload a pdf template" in Sign: create a document that is signable
- "New allocation request" in Time Off: allow to create an allocation request record from the holiday view
- etc.

Note that only 12 list views  and 4 kanban views have this kind of buttons, so this is indeed an exception - we will probably remove a few of those soon but i don't think we should block for this, to be honest
![image](https://user-images.githubusercontent.com/9530767/236144253-f1dac6a5-6123-4383-9fcc-deb16c390168.png)


I agree that some of those should move to the cog button, but in the mean time we agreed with fp that always buttons should be next the to new button since they are (supposed to be) closely related, and in mobile it makes sense to merge them into a dropdown in that case (because indeed you are normally creating "other kinds of records" (or using a wizard to create stuff en masse, or import them, etc)

In larger screens, it tend to take up a lot of real estate in some cases (having 5 buttons before your breadcrumb is weird indeed and should be an exception), but this we will modify app per app. We currently lack a mechanism to easily integrate them in the dropdown, hence the current solution.

Note that my commit does not introduce the behaviour, it just make it happen sooner

2023-05-04 08:33 UTC, stefanorigano requested changes
> with fp we established that "always" buttons are (or, more accurately; should be) akin to "new" buttons

mmm..  debatable but I see what you mean.
Maybe we could to at least reword a bit on mobile (eg. Request -> New Request ), so they will not look out of context... but we can see later on ;)

LGTM, just a minor remark in the code. I propose to wait for master-milk to be "push--forced" 
 (it will be soon) and then rebase this and merge this. ok?
 Unless you have still to work on it ofc.

2023-05-04 08:33 UTC, stefanorigano commented on addons/web/static/src/search/control_panel/control_panel.scss
> +    .o_control_panel_actions:empty {
You can use the new `d-empty-none` utility-class ;)

2023-05-04 10:50 UTC, bouvyd commented
Changes applied, rebase done and tested in runbot-all, merging now to avoid rebase-hell

2023-05-04 10:50 UTC, merged