[IMP] hr_skills: fix ::before alignment
odoo-dev/odoo pull request #2476
Opened 2023-05-04 14:31 UTC by chgo-odoo

This PR is related to this issue in the pad : 

**[CHGO][GMF] Employee Resume lines, the dot should be on the line https://i.imgur.com/XRQ3eoE.png** 

== ISSUE ==

Before this commit, the `:before` line in Employee resume is not aligned with the dots. This is due to the fact that the variable `$o-hrs-timeline-entry-padding` used in the mixin isn't the right value we should use.

There was also an issue with responsive.

== After this commit ==

We now use a calc, which process the half of the circle plus the padding minus the border-width.

We adapt this in a smaller media query since the `$o-horizontal-padding` value is different.

2023-05-04 14:32 UTC, robodoo commented
This PR targets the un-managed branch odoo-dev/odoo:master-milk, it needs to be retargeted before it can be merged.

2023-05-04 14:32 UTC, chgo-odoo commented
Hi @stefanorigano 👋

Here is a PR related to the border alignment issue, could you have a look at it?

Thanks !

2023-05-05 07:49 UTC, stefanorigano requested changes

2023-05-05 07:49 UTC, stefanorigano commented on addons/hr_skills/static/src/fields/resume_one2many.scss
> +                @include o-position-absolute(0, $left: calc(#{$o-hrs-timeline-dot-size} * .5 + #{$o-horizontal-padding} - #{$border-width} ));
Well done, but in general better to avoid `calc()`.
We introduced a new sass function `o-to-rem()`, you can use that instead

2023-05-05 07:49 UTC, stefanorigano commented on addons/hr_skills/static/src/fields/resume_one2many.scss
> +                    @include o-position-absolute(0, $left: calc(#{$o-hrs-timeline-dot-size} * .5 + #{$o-horizontal-padding} * 2 - #{$border-width} ));
You can override `left` only, without re-generate all the other mixin's rules   
```suggestion
                    left: [your value];
```

2023-05-05 07:53 UTC, stefanorigano commented
Commit and PR's description well written, very good 👍 
Just one remark about the reference you did to the before pseudo-element: wrap the word between ` symbols so github we'll rendered it properly. 

::before vs `::before`

2023-05-05 07:53 UTC, stefanorigano commented
... and add the task's id ;)

2023-05-05 08:16 UTC, chgo-odoo commented
@stefanorigano Changes done, could you have a look, thanks 👍

2023-05-05 08:25 UTC, merged

2023-05-05 08:26 UTC, robodoo commented
This PR targets the un-managed branch odoo-dev/odoo:master-milk, it needs to be retargeted before it can be merged.

2023-05-05 08:26 UTC, stefanorigano commented
Very good, thanks 👍