[FIX] mail: only active users could be used for chat window creation
odoo-dev/odoo pull request #274
Opened 2020-06-08 14:03 UTC by xdu-odoo

task-2263679

2020-06-08 15:54 UTC, alexkuhn requested changes
Runbot red (im livechat typing notification test fails)

2020-06-08 17:24 UTC, seb-odoo commented on addons/im_livechat/static/src/messaging/component/thread_icon/thread_icon_tests.js
> +        },
alphabetical, space after id:

2020-06-08 17:24 UTC, seb-odoo commented on addons/mail/models/res_partner.py
> +        return {
add self.ensure_one

2020-06-08 17:24 UTC, seb-odoo commented on addons/im_livechat/static/src/messaging/component/thread_textual_typing_status/thread_textual_typing_status_tests.js
> +        },
same

2020-06-08 17:24 UTC, seb-odoo commented on addons/mail/static/src/messaging/test_utils.js
> +            },
same

2020-06-08 17:24 UTC, seb-odoo commented on addons/mail/static/tests/helpers/mock_server.js
> +            },
same

2020-06-09 09:31 UTC, seb-odoo commented on addons/im_livechat/static/src/messaging/component/thread_textual_typing_status/thread_textual_typing_status_tests.js
> +            id :7,
space after : not before

2020-06-09 09:32 UTC, seb-odoo commented on addons/mail/static/tests/helpers/mock_server.js
> +                id:2,
space

2020-06-09 11:48 UTC, seb-odoo approved these changes
I didn't test but code looks ok.

We'll probably have to add "active" in more formatters to cover more cases (actual archived partners in message fetch, etc) but this can be done later/when the need arises.

cc @alexkuhn you can check this

2020-06-09 14:39 UTC, alexkuhn approved these changes

2020-06-09 14:53 UTC, merged