[IMP] pos_customer_display: UI Improvements
odoo-dev/odoo pull request #2992
Opened 2024-03-19 14:39 UTC by xlu-odoo

Prior to this commit, following recent changes integrating Bootstrap to
the customer display, the layout was lacking refinement and required a 
layout overhaul. This update addresses and improves the UI.

task-3773289

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2024-03-19 14:40 UTC, robodoo commented
This PR targets the un-managed branch odoo-dev/odoo:master-pos_customer_display_standalone_app-vlst, it needs to be retargeted before it can be merged.

2024-03-26 14:28 UTC, anso-odoo reviewed
Thanks for your work, it looks really nice ! I left some comments for you 👍

2024-03-26 14:28 UTC, anso-odoo commented on addons/pos_customer_display/static/src/app/styles.scss
> +        height: 5rem;
Logo ratio is broken in sub-md resolution. Maybe put a max height on the image instead ? 
![Screenshot 2024-03-25 at 10 05 44](https://github.com/odoo-dev/odoo/assets/110090660/ba1248e5-8a0d-47a2-a3c6-84c1900c5665)

2024-03-26 14:28 UTC, anso-odoo commented on addons/pos_customer_display/static/src/app/root.xml
> +                    <table t-if="order.amount" t-attf-class="table table-dark table-borderless table-sm w-75 w-sm-50 w-xl-25 m-3 ms-md-auto ms-auto text-end">
Can't we drop ms-md-auto ?

2024-03-26 14:28 UTC, anso-odoo commented on addons/pos_customer_display/static/src/app/root.xml
> +                                <th scope="col">Total</th>
The labels here are moving when we add content. Can't we fix the size of the columns (at least with a min-width) ?
https://tinyurl.com/4c6497nm

2024-04-09 12:04 UTC, anso-odoo approved these changes
I left a small comment, but overall LGTM !

2024-04-09 12:04 UTC, anso-odoo commented on addons/pos_customer_display/static/src/app/root.xml
> +            <div class="o_customer_display_sidebar d-flex flex-column flex-basis-md-25 align-items-center justify-content-between gap-2 gap-md-0 px-2 px-md-4 py-4 bg-700" t-att-style="session.has_bg_
I think here we may just simplify the padding classes to p-4

2024-04-16 11:38 UTC, xlu-odoo commented
When you have time, could you please check this one @stefanorigano

2024-04-25 07:48 UTC, stefanorigano requested changes
Hello @xlu-odoo , thanks for you work 👍 

Code is mostly ok, but I think that the design needs to be reviewed.
I wrote some remarks in the code, but it would be better to iterate a bit on Figma first and apply the design once it's confirmed. 

Thanks!

2024-04-25 07:48 UTC, stefanorigano commented on addons/pos_customer_display/static/src/app/root.xml
> +                <div t-if="!order.finalized and order.lines?.length" class="d-flex px-4 py-1 text-bg-dark">
To double check with the PO, but the "Your Order" bar looks unnecessary
| this PR | Suggestion |
|--------|--------|
| ![image](https://github.com/odoo-dev/odoo/assets/8558351/b32122a0-92dc-4e43-95d7-2c707769e712) | ![image](https://github.com/odoo-dev/odoo/assets/8558351/a0df479e-9b2d-4327-a331-9026d93da131) |

2024-04-25 07:48 UTC, stefanorigano commented on addons/pos_customer_display/static/src/app/root.xml
> +                    <Orderline line="scope.line" imgSize="'4rem'" infoListClasses="''" class="'o_customer_display_orderline d-flex align-items-center mx-2 my-1 ps-1 pe-3 rounded-3 bg-white fs-3' + (s
I find the overall design-line too "bulky".
At 1280x720 res, we can list 7 items only, it's not enough IMO. I think that we don't need cards...
Lightspeed and squareup are good examples of how these lists can be deeply simplified.

| Current | raw test |
|--------|--------|
| ![image](https://github.com/odoo-dev/odoo/assets/8558351/b32122a0-92dc-4e43-95d7-2c707769e712)| ![image](https://github.com/odoo-dev/odoo/assets/8558351/795646a4-1ec4-4988-86e1-3d17779b0dff) |

2024-05-28 13:47 UTC, closed without merging