[IMP] payment_sips: adapt to the new payment API
odoo-dev/odoo pull request #488
Opened 2020-11-13 08:33 UTC by kba-odoo

TaskID: 2333041

2020-11-23 18:17 UTC, AntoineVDV requested changes
I pushed an additional --fixup commit of cosmetic changes, feel free to discard if you disagree o/

2020-11-23 18:17 UTC, AntoineVDV commented on addons/payment_sips/models/payment_acquirer.py
> +from odoo.tools.translate import _
import from odoo

2020-11-23 18:17 UTC, AntoineVDV commented on addons/payment_sips/models/payment_acquirer.py
> +from odoo.addons.payment.models.payment_acquirer import ValidationError
import from odoo.exceptions

2020-11-23 18:17 UTC, AntoineVDV commented on addons/payment_sips/models/payment_acquirer.py
> +class AcquirerSips(models.Model):
Absolute nitpicking:
```suggestion
class PaymentAcquirer(models.Model):
```
So that the class name matches the model

2020-11-23 18:17 UTC, AntoineVDV commented on addons/payment_sips/models/payment_acquirer.py
> +        default=2)
`groups='base.group_system'`

2020-11-23 18:17 UTC, AntoineVDV commented on addons/payment_sips/models/payment_acquirer.py
> +        default="https://payment-webinit.sips-atos.com/paymentInit")
I guess that these two could be hard-coded.

2020-11-23 18:17 UTC, AntoineVDV commented on addons/payment_sips/models/payment_acquirer.py
> +        default="HP_2.31")
I'm not sure to understand what this is. Is it some sort of API version (that we should then hard-code), or the version of the merchant account somehow?

2020-11-23 18:17 UTC, AntoineVDV commented on addons/payment_sips/models/payment_acquirer.py
> +    def _sips_supported_currencies(self):
Nitpicking:
```suggestion
    def _sips_get_supported_currencies(self):
```
Also, the method doesn't seem to be super useful since its only purpose is to cast a namedtuple as a recordset, and it is only called once.

2020-11-23 18:17 UTC, AntoineVDV commented on addons/payment_sips/models/payment_acquirer.py
> +        acquirers = super()._get_compatible_acquirers(company_id, partner_id, currency_id, allow_tokenization, preferred_acquirer_id, **kwargs)
```suggestion
    def _get_compatible_acquirers(self, *args, currency_id=None, **kwargs):
        acquirers = super()._get_compatible_acquirers(*args, currency_id=currency_id, **kwargs)
```
This can be simplified and made more robust to changes in the super method.

2020-11-23 18:17 UTC, AntoineVDV commented on addons/payment_sips/models/payment_acquirer.py
> +            acquirers = acquirers - sips
We can save some requests and pre-fetching by making sure that SIPS is included in the list of compatible acquirers before searching on `res.currency`. Additionally, there is no need to search nor include SIPS if the `currency_id` is not set (can happen when managing tokens). Using `filtered` instead of searching on `payment.acquirer` also (trivially) saves a request.
```suggestion
        if currency_id and 'sips' in acquirers.mapped('provider'):
            if self.env['res.currency'].browse(currency_id).name not in SIPS_SUPPORTED_CURRENCIES:
                acquirers = acquirers.filtered(lambda a: a.provider != 'sips')
        return acquirers
```
There may be a better way to do this with a `filtered_domain` but, unless the concerned tables are really big,  readability > performance

2020-11-23 18:17 UTC, AntoineVDV commented on addons/payment_sips/models/const.py
> +
*referring to the namedtuple above*

The new best practice is to rely on `res.currency` and its `decimal_places` field to get the number of decimals of a currency. Unfortunately, we don't have a field for the ISO number (`iso_id` here).

We can at least remove the hard-coded values for the decimals. Yet, it's important to make sure that the decimal values that SIPS rely upon actually follow the real ISO values. If that's not the case (for example, [Adyen gives a list of currencies for which the decimals are different than that of ISO](https://docs.adyen.com/development-resources/currency-codes)), the SIPS value should be hard-coded when it differs from ISO.

I leave it up to you to decide whether a `namedtuple` is still relevant here, or if two dict can do the trick.
I attach a [CSV file of the ISO number of decimals for each currency](https://github.com/odoo-dev/odoo/files/5584342/all.txt). You can discard the 'Odoo' column and `-1` values.

2020-11-23 18:17 UTC, AntoineVDV commented on addons/payment_sips/models/payment_transaction.py
> +import datetime
unused import

2020-11-23 18:17 UTC, AntoineVDV commented on addons/payment_sips/models/payment_transaction.py
> +from odoo.tools.translate import _
import from odoo

2020-11-23 18:17 UTC, AntoineVDV commented on addons/payment_sips/models/payment_transaction.py
> +from odoo.addons.payment.models.payment_acquirer import ValidationError
import from odoo.exceptions

2020-11-23 18:17 UTC, AntoineVDV commented on addons/payment_sips/models/payment_transaction.py
> +from hashlib import sha256
unused imports

2020-11-23 18:17 UTC, AntoineVDV commented on addons/payment_sips/models/payment_transaction.py
> +from .const import SIPS_SUPPORTED_CURRENCIES, SIPS_STATUS_CANCEL, SIPS_STATUS_PENDING, SIPS_STATUS_ERROR, SIPS_STATUS_REFUSED, SIPS_STATUS_VALID, SIPS_STATUS_WAIT
```suggestion
from .const import SIPS_SUPPORTED_CURRENCIES, SIPS_STATUS_CANCEL, SIPS_STATUS_PENDING, \
    SIPS_STATUS_ERROR, SIPS_STATUS_REFUSED, SIPS_STATUS_VALID, SIPS_STATUS_WAIT
```

2020-11-23 18:17 UTC, AntoineVDV commented on addons/payment_sips/models/payment_transaction.py
> +class TxSips(models.Model):
Nitpicking (same as above)
```suggestion
class PaymentTransaction(models.Model):
```

2020-11-23 18:17 UTC, AntoineVDV commented on addons/payment_sips/models/payment_transaction.py
> +            prefix = singularize_reference_prefix(separator='')
Why not pass the separator overwritten above?

2020-11-23 18:17 UTC, AntoineVDV commented on addons/payment_sips/models/payment_transaction.py
> +    def _get_specific_processing_values(self, processing_values):
You shouldn't need to override this method. Instead, everything could be done in `_get_specific_rendering_values` since everything is computed in order to build the rendering context.

2020-11-23 18:17 UTC, AntoineVDV commented on addons/payment_sips/models/payment_transaction.py
> +        currency = self.env["res.currency"].sudo().browse(processing_values["currency_id"])
Is this `sudo` needed?

2020-11-23 18:17 UTC, AntoineVDV commented on addons/payment_sips/models/payment_transaction.py
> +                _("Currency not supported by Wordline: %s") % currency.name
```suggestion
                "SIPS: " + _("this currency is not supported: %s", currency.name)
```

2020-11-23 18:17 UTC, AntoineVDV commented on addons/payment_sips/models/payment_transaction.py
> +        amount = round(processing_values["amount"] * (10 ** sips_currency.decimal))
Use `payment.utils.to_minor_currency_units`.
As discussed above, you may have currencies for which SIPS uses a different number of decimals than the ISO standard. For those currencies, make use of the `arbitrary_decimal_number` argument to force the value (see Adyen for examples).

2020-11-23 18:17 UTC, AntoineVDV commented on addons/payment_sips/models/payment_transaction.py
> +        if sips_tx_values.get("return_url"):
Where would the `return_url` value come from?

2020-11-23 18:17 UTC, AntoineVDV commented on addons/payment_sips/models/payment_transaction.py
> +            return super()._get_tx_from_data(provider, data)
```suggestion
            return super()._get_tx_from_feedback_data(provider, data)
```

2020-11-23 18:17 UTC, AntoineVDV commented on addons/payment_sips/models/payment_transaction.py
> +                _("Sips: received data for reference %s; no order found") % reference
```suggestion
                "Sips: " + _("received data for reference %s; no order found", reference)
```

2020-11-23 18:17 UTC, AntoineVDV commented on addons/payment_sips/models/payment_transaction.py
> +            raise ValidationError(error_msg)
```suggestion
            raise ValidationError("Sips: " + _("received data for reference %s; no order found", reference))
```

2020-11-23 18:17 UTC, AntoineVDV commented on addons/payment_sips/models/payment_transaction.py
> +        )
Use `to_major_currency_units` (will be added asap)

2020-11-23 18:17 UTC, AntoineVDV commented on addons/payment_sips/models/payment_transaction.py
> +            raise ValidationError(_('Incorrect amount: received %.2f, expected %.2f', amount_converted, tx.amount))
Take advantage of the new translation function feature to name your variable and allow swapping them in translations.
NB: I'm unsure whether this works with `%.2f`, to test :p

2020-11-23 18:17 UTC, AntoineVDV commented on addons/payment_sips/models/payment_transaction.py
> +                date = fields.Datetime.now()
```suggestion
```
`date` is not used, is it intended?

2020-11-23 18:17 UTC, AntoineVDV commented on addons/payment_sips/models/payment_transaction.py
> +            self._set_canceled()
```suggestion
            msg = f"ref: {self.reference}, got unrecognized response [{status}], set as error."
            self._set_error("insert error message shown to customer here")
```

2020-11-23 18:17 UTC, AntoineVDV commented on addons/payment_sips/controllers/main.py
>      @http.route('/payment/sips/dpn', type='http', auth="public", methods=['POST'], csrf=False)
```suggestion
    @http.route(_return_url, type='http', auth="public", methods=['POST'], csrf=False)
```
same for `_notify_url`

2020-11-23 18:17 UTC, AntoineVDV commented on addons/payment_sips/controllers/main.py
>      @http.route('/payment/sips/dpn', type='http', auth="public", methods=['POST'], csrf=False)
```suggestion
    @http.route('/payment/sips/dpn', type='http', auth="public", methods=['POST'])
```
CSRF token is not checked for 'safe' HTTP methods such as `POST`.

2020-11-23 18:17 UTC, AntoineVDV commented on addons/payment_sips/controllers/main.py
>              _logger.info('Beginning Sips DPN form_feedback with post data %s', pprint.pformat(post))  # debug
```suggestion
            _logger.info('Beginning Sips DPN _handle_feedback_data with post data %s', pprint.pformat(post))
```
useless comment is useless + `form_feedback` no longer exists -> same for `sips_ipn`

2020-11-23 18:17 UTC, AntoineVDV commented on addons/payment_sips/controllers/main.py
> +        sips = request.env['payment.acquirer'].sudo().search([('provider', '=', 'sips')], limit=1)
You cannot know which acquirer will be the right one: there could be several acquirers (one per company) sharing the same provider.
Use `tx_sudo = self.env['payment.transaction].sudo()._get_tx_from_feedback_data(...) ; acquirer_sudo = tx_sudo.acquirer_id`

2020-11-23 18:17 UTC, AntoineVDV commented on addons/payment_sips/controllers/main.py
> +            return request.env['payment.transaction'].sudo()._handle_feedback_data(data=post, provider='sips')
```suggestion
            return request.env['payment.transaction'].sudo()._handle_feedback_data('sips', post)
```

2020-11-24 08:15 UTC, kba-odoo commented on addons/payment_sips/models/payment_transaction.py
> +            prefix = singularize_reference_prefix(separator='')
Just for aesthetic reasons :smile: 
The singularized prefix would then be "tx**x**1234567890"

2020-11-24 08:25 UTC, kba-odoo commented on addons/payment_sips/models/payment_transaction.py
> +        if sips_tx_values.get("return_url"):
Leftover from the old code :speak_no_evil:

2020-12-02 13:44 UTC, AntoineVDV commented on addons/payment_sips/models/payment_transaction.py
> +            prefix = singularize_reference_prefix(separator='')
Makes sense :+1:

2020-12-02 17:31 UTC, AntoineVDV approved these changes
![4onjr9](https://user-images.githubusercontent.com/15896813/100909070-8c7e6b00-34cc-11eb-839c-092ba26ff9a7.jpg)

2020-12-02 17:31 UTC, merged