Discuss Sidebar: Implement default avatar
odoo-dev/odoo pull request #999
Opened 2021-07-08 14:17 UTC by qho-odoo

- Channels
    * hash tag avatar with different backgroud colors
    * only private channels have lock thread icon
- DM groups
    * users avatar with different background colors
    * no thread icon

2021-07-08 14:17 UTC, robodoo commented
This PR targets the un-managed branch odoo-dev/odoo:master-discuss-v15, it can not be merged.

2021-07-12 14:35 UTC, robodoo commented
This PR targets the un-managed branch odoo-dev/odoo:master-discuss-v15, it can not be merged.

2021-08-05 16:29 UTC, seb-odoo commented
Could you please rebase? I have recently updated the target branch.

2021-08-06 11:04 UTC, qho-odoo commented
> Could you please rebase? I have recently updated the target branch.

Rebased

2021-08-06 17:07 UTC, seb-odoo requested changes
Thank you for the PR. First validation, some comments but overall the code and result is pretty good already.

2021-08-06 17:07 UTC, seb-odoo commented on addons/mail/models/mail_channel.py
> +    @api.depends('image_128', 'channel_type')
technically the generated avatar also depends on name and create_date

2021-08-06 17:07 UTC, seb-odoo commented on addons/mail/models/mail_channel.py
> +            avatar_path = "mail/static/src/img/channel.svg"
In the avatar mixin the svg is actually stored directly in python for performance reasons for not reading the disk, I wonder if we shouldn't do the same here. But as its content is quite a bit more complex, we'd need to find a way to do it that is not too verbose (maybe define it in a variable at the top of the file instead of inline of the method?)

2021-08-06 17:07 UTC, seb-odoo commented on addons/mail/models/mail_channel.py
> +            self._notify_channel_avatar_changed()
Technically as the name and channel_type (and create_date but that can't be changed) as has an influence on the generated image, the notify should also happen when they are changed.

Is it possible to also catch changes in avatar_128 due to compute here?

2021-08-06 17:07 UTC, seb-odoo commented on addons/mail/models/mail_channel.py
> +            self.env['bus.bus'].sendone((self._cr.dbname, 'mail.channel', channel.id), {
use sendmany and no loop instead

2021-08-06 17:07 UTC, seb-odoo commented on addons/mail/models/mail_channel.py
> +                'type': 'channel_avatar_changed',
would prefix with `mail.` (same for bus notif in the sidebar pr actually, I forgot to say it)

2021-08-06 17:07 UTC, seb-odoo commented on addons/mail/static/src/components/discuss/tests/discuss_tests.js
> -    );
Shouldn't it test that it has avatar instead?

2021-08-06 17:07 UTC, seb-odoo commented on addons/mail/static/src/components/discuss_sidebar_category_item/discuss_sidebar_category_item_tests.js
> +    });
keep single line here

2021-08-06 17:07 UTC, seb-odoo commented on addons/mail/static/src/components/discuss_sidebar_category_item/discuss_sidebar_category_item_tests.js
> +
no need for extra new line

2021-08-06 17:07 UTC, seb-odoo commented on addons/mail/static/src/components/discuss_sidebar_category_item/discuss_sidebar_category_item_tests.js
> +    // Stub Date.now for testing.
The _what_ is pretty obvious, it would be nice to explain _why_ it needs to be done.

2021-08-06 17:07 UTC, seb-odoo commented on addons/mail/static/src/components/discuss_sidebar_category_item/discuss_sidebar_category_item_tests.js
> +    });
also single line

2021-08-06 17:07 UTC, seb-odoo commented on addons/mail/static/src/components/discuss_sidebar_category_item/discuss_sidebar_category_item_tests.js
> +    );
It would be better to assert what it currently is, instead of what it is not.

2021-08-06 17:07 UTC, seb-odoo commented on addons/mail/static/src/components/discuss_sidebar_category_item/discuss_sidebar_category_item_tests.js
> +    });
Prefer to use mock server and a real user interaction that changes avatar.

2021-08-06 17:07 UTC, seb-odoo commented on addons/mail/static/src/components/discuss_sidebar_category_item/discuss_sidebar_category_item_tests.js
> +
no need for extra new line

2021-08-06 17:07 UTC, seb-odoo commented on addons/mail/static/src/models/discuss_sidebar_category_item/discuss_sidebar_category_item.js
> +            dependencies: ['channelAvatarUnique'],
dependencies are no longer necessary for compute to work, you can remove them all

2021-08-06 17:07 UTC, seb-odoo commented on addons/mail/static/src/models/discuss_sidebar_category_item/discuss_sidebar_category_item.js
> +                    return this.channelPublic === 'private';
don't use related field, directly access channel here

2021-08-06 17:07 UTC, seb-odoo commented on addons/mail/static/src/models/discuss_sidebar_category_item/discuss_sidebar_category_item.js
> +        }),
avoid related, no longer necessary for compute

2021-08-06 17:07 UTC, seb-odoo commented on addons/mail/static/src/models/messaging_notification_handler/messaging_notification_handler.js
> +            channel.update({ avatarUnique: Date.now() });
this is better than nothing but not really correct, ideally this should use something from the server that doesn't change after every page refresh to keep a true cache of the image (such as `write_date` field on channel ?)

2021-08-06 17:07 UTC, seb-odoo commented on addons/mail/static/src/models/thread/thread.js
> +        avatarUnique: attr({
alphabetical order, also I would rename to `avatarCacheKey` or something similar, because just "avatar unique" looks like it is a setting to have a unique avatar (in terms of having only one, whatever that means)

2021-08-06 17:07 UTC, seb-odoo commented on addons/mail/static/src/models/thread/thread.js
> +         * An unique integer to force a reload of the avatar when the avatar is changed.
add comment that it only makes sense on channels

2021-08-06 17:07 UTC, seb-odoo commented on addons/mail/static/src/models/thread/thread.js
> +            default: Date.now(),
if we can get rid of using date in js it would be better as suggested above

2021-08-06 17:07 UTC, seb-odoo commented on addons/mail/tests/test_mail_channel.py
> +        channel.create_date = datetime(2021, 1, 1)
Wait did that actually work? I thought this field was read only in the orm.

2021-08-06 17:07 UTC, seb-odoo commented on addons/mail/tests/test_mail_channel.py
> +    def test_channel_write_should_send_notification_if_image_128_presents(self):
"presents"? "changed" maybe?

2021-08-06 17:07 UTC, seb-odoo commented on addons/mail/tests/test_mail_channel.py
> +        with self.assertBus([(self.cr.dbname, 'mail.channel', channel.id)]):
also assert bus content

2021-08-26 15:49 UTC, qho-odoo commented on addons/mail/models/mail_channel.py
> +            self._notify_channel_avatar_changed()
computed field is not caught in `write()`

2021-08-26 15:50 UTC, qho-odoo commented on addons/mail/static/src/components/discuss/tests/discuss_tests.js
> -    );
avatar has been tested in category_item_test

2021-08-26 15:50 UTC, qho-odoo commented on addons/mail/tests/test_mail_channel.py
> +        channel.create_date = datetime(2021, 1, 1)
Yes, create_date is not read only actually

2021-08-26 15:51 UTC, qho-odoo commented
@seb-odoo 
Please check the new PR target on the master branch: https://github.com/odoo/odoo/pull/75653 :)

2021-08-26 15:52 UTC, closed without merging